### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by svenluijten** [jeffochoa/factory-stories#1]
Consider adding a LICENSE file to the repository. [This blogpost](https://github.com/blog/1530-choosing-an-open-source-license) is a great rundown of how you can (and should) choose how to license your code 🙂

**Comment by jeffochoa** [comment]
Thanks Sven!! I'll do that

**Comment by jeffochoa** [comment]
I just added the LICENCE file https://github.com/jeffochoa/factory-stories/blob/master/LICENSE
