### ISSUE TITLE
Is there something missing about namespacing?

### ISSUE THREAD

**Issue by eduarguz** [jeffochoa/factory-stories#9]
I can see that the stub class doesn't include a namespace, which is ok, but I cannot find a way to import the stories

1. should I add the stories path to the `composer.json`
```
"autoload": {
        "classmap": [
            "database/seeds",
            "database/factories",
+          "database/stories"
        ],
},
```

is it ok to go that way? should be included in readme?

**Comment by jeffochoa** [comment]
Here you can see an example of how to use it in your tests files [https://github.com/jeffochoa/factory-stories/blob/master/tests/FactoryTest.php](https://github.com/jeffochoa/factory-stories/blob/master/tests/FactoryTest.php)
